version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 12
  build:
    commands:
      - npm ci
      - export BUCKET=<OUTPUT BUCKET>     
      - aws cloudformation package --template-file CFtemplate.json --s3-bucket $BUCKET --s3-prefix codepipeline --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml
